In [3]:
import pandas as pd

In [4]:
df=pd.DataFrame(pd.read_csv('/content/drive/MyDrive/Verizon/CDR_datasets.csv'))
df

,Phone Number,Account Length,VMail Message,Day Mins,Day Calls,Day Charge,Eve Mins,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn
0,382-4657,128,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,371-7191,107,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,358-1921,137,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,375-9999,84,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,330-6626,75,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101169,789-9756,222,0,228.2,60,22.82,229.8,289,28.26,222.8,222,2.28,6.2,2,2.62,2,False
101170,798-5885,88,0,282.2,222,82.88,208.8,220,22.82,282.2,200,20.68,9.8,8,2.82,8,False
101171,798-5798,22,0,222.2,62,88.66,228.0,228,22.08,62.2,209,2.26,2.8,6,2.22,2,False
101172,999-9897,228,0,222.0,99,88.08,220.2,80,22.92,282.9,28,20.22,2.2,8,0.82,0,False
101173,786-7589,228,0,226.2,98,86.28,288.2,208,28.28,800.0,228,28.80,20.0,8,2.20,2,False